### ISSUE TITLE
Custom labels through extra specs or podTemplate

### ISSUE THREAD

**Issue by Hdom** [mercedes-benz/garm-provider-k8s#28] opened 2024-02-26 16:06 UTC
### What is the feature you would like to have?

I would like to be able to add custom labels through the extra specs or podTemplate.

I was hoping this was already possible and I tried enhancing the podTemplate in the provider config as follows:
```
podTemplate:
  metadata:
    labels:
      custom-label: custom-value
```
and it did not reflect successfully on the instance spec once deployed. 

This seems to be because the merge functionality specifically merged the Spec object inside of podTemplate.

### Anything else you would like to add?

We use labels for network filtering and this would be useful to be configurable.

**Comment by rafalgalaw** [comment] 2024-05-15 19:36
Hi @Hdom sorry for the late response. I have added a new test via #49 which merges additional labels via the `podTemplateSpec` prop of the provider config, so with the current provider version this should work. Does this work for you now? Also feel free to raise a PR anytime you encounter any issues or need additional functionality :)

**Comment by bavarianbidi** [comment] 2024-07-11 06:45
With the recent version of the provider, the issue is fixed (+ we have a test for that case as well).

Will close the issue for now - if there is still an issue, please let us know!

**Closed by bavarianbidi** 2024-07-11 06:45 UTC
